name: Build and Package
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build and generate artifact
      run: |
        # Example build command (replace with your build process)
        ./build.sh
        
        # Create an artifact directory and copy the build output
        mkdir -p artifacts
        cp build_output/* artifacts/
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my_artifact
        path: artifacts/
Explanation:

Trigger:

The workflow triggers on every push to the main branch.
Jobs:

Defines a single job named build that runs on the latest Ubuntu environment.
Steps:
a. Checkout code:

Checks out the repository code.
b. Build and generate artifact:

Represents the build process (replace with your actual build commands).
Creates a directory named artifacts and copies the build output (e.g., executable, archive) into it.
c. Upload artifact:

Uses the upload-artifact action to upload the content of the artifacts directory as an artifact.
The artifact is named "my_artifact" and includes the contents of the artifacts/ directory.
This workflow, when triggered by a push to the main branch, will execute the specified build process, generate artifacts, and upload them for later use, testing, or deployment.

In a real-world scenario, the build commands and artifact paths will vary based on the specific project's build process and requirements. The artifacts created here could be used in subsequent steps for testing, deployment, or any other necessary processes in the CI/CD pipeline.




